Echange Livres/Models/WishListe.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Application_Echange_de_livre.Model
{
    public class WishListe
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int BookId { get; set; }

        public virtual User User { get; set; }
        public virtual Book Book { get; set; }
    }
}

Echange Livres/Controllers/WishListeController.cs
using Application_Echange_de_livre.Model;
using Echange_Livres.Repositories;
using Echange_Livres.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Echange_Livres.Controllers
{
    public class WishListeController : Controller
    {
        private WishListeService Wservice = new WishListeService(new WishListeRepository(new MyContext()));
        private MyContext context = new MyContext();

        // GET: WishListe
        public ActionResult Index()
        {
            List<WishListe> lstWish = Wservice.GetAll();
            return View(lstWish);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id")] WishListe wish)
        {
            if (ModelState.IsValid)
            {
                Wservice.Add(wish);
                return RedirectToAction("Index");
            }

            return View(wish);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WishListe wish = context.WishListes.Find(id);

            if (wish == null)
            {
                return HttpNotFound();
            }
            return View(wish);

        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
           WishListe wish = context.WishListes.Find(id);
            Wservice.Delete(wish);
            return RedirectToAction("Index");
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WishListe wish = context.WishListes.Find(id);
            if (wish == null)
            {
                return HttpNotFound();
            }
            return View(wish);
        }

    }
}

Echange Livres/Views/WishListe/Create.cshtml
@model Application_Echange_de_livre.Model.WishListe

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WishListe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookId, "BookId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BookId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BookId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Echange Livres/Views/WishListe/Delete.cshtml
@model Application_Echange_de_livre.Model.WishListe

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to remove this from your wish liste ?</h3>
<div>
    <h4>WishListe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Book.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Book.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
<style>
    input[type=text], select {
        width: 50%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 60%;
        background-color: #6a64f1;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #6a64f1;
        }

    div {
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 20px;
    }
</style>

Echange Livres/Views/WishListe/Details.cshtml
@model Application_Echange_de_livre.Model.WishListe

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>WishListe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Book.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Book.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Book.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Book.Photo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<style>
    input[type=text], select {
        width: 50%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 60%;
        background-color: #6a64f1;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #6a64f1;
        }

    div {
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 20px;
    }
</style>

Echange Livres/Views/WishListe/Index.cshtml
@model IEnumerable<Application_Echange_de_livre.Model.WishListe>

@{
    ViewBag.Title = "Index";
}

<h2>My Wish Liste</h2>
<br />
<br />
<div class="container">
    <p>
        @using (Html.BeginForm("Index", "WishListe", FormMethod.Get))
        {
            <div class="col-sm-6">
                <input type="text" name="search" placeholder="mot clé...." class="form-control" />
            </div><br />
            <div class="col-sm-6">
                <input type="submit" value="Rechercher" style="color: #6a64f1" />
            </div>
        }

    </p>
</div>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table id="wishliste">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Book.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Book.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

<style>

    #wishliste {
        font-family: Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 60%;
    }

        #wishliste td, #wishliste th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        #wishliste tr:nth-child(even) {
            background-color: #f7f0f0;
        }

        #wishliste tr:hover {
            background-color: #dbc0e6;
        }

        #wishliste th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #9a7be8;
            color: white;
        }
</style>